# config for https://houndci.com
scss:
  enabled: false

rubocop:
  enabled: false

eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore

jshint:
  enabled: true
  ignore_file: .javascript_ignore
  # config_file: .jshintrc

coffeescript:
  enabled: false

flake8:
  enabled: true
  config_file: .flake8.ini

shellcheck:
  enabled: true
  config_file: .shellcheck.yml
